---
# This playbook cleans up a mahine after full/partial contiv k8s install

- hosts: all
  sudo: yes
  vars:
    etc_host_entries: "{{ lookup('file', '.etc_hosts') }}"
    ssh_username: cloud 

  tasks:

  - name: Cleanup | clean up ovs state
    shell: ovs-vsctl del-br {{ item }}
    with_items:
     - contivVxlanBridge
     - contivVlanBridge
     - contivHostBridge
    ignore_errors: yes
    tags:
      - erase_state

  - name: Cleanup | clean up ports
    shell: for p in `ifconfig  | grep {{ item }} | awk '{print $1}'`; do sudo ip link delete $p type veth; done
    with_items:
     - vport
     - hport
     - contivh0
    ignore_errors: yes
    tags:
      - erase_state

  - name: Cleanup | stop services started for k8s-contiv
    service: name="{{ item }}" state=stopped
    with_items:
     - kubelet
     - kube-proxy
     - docker
     - netmaster
     - aci-gw
     - netplugin
     - kube-scheduler
     - kube-apiserver
     - kube-kube-controller-manager
     - etcd
    ignore_errors: yes
    tags:
      - stop

  - name: Cleanup | clean up /etc/hosts node entries
    lineinfile: dest=/etc/hosts regexp='.*       ' state=absent
    tags:
      - etc_hosts

  - name: Cleanup | clean up /etc/hosts netmaster entry
    lineinfile: dest=/etc/hosts regexp=.*netmaster$ state=absent
    tags:
      - etc_hosts

  - name: Cleanup | Unistall etcd
    yum: name=etcd state=removed
    tags:
      - etcd_uninstall
    
  - name: Cleanup | Remove config files added by k8s-contiv
    file: path={{ item }} state=absent
    with_items:
      - /etc/systemd/system/etcd.service
      - /var/lib/etcd
      - /etc/etcd/etcd.conf
      - /etc/kubernetes/certs
      - /opt/cni/bin
      - /opt/contiv
      - /usr/libexec/kubernetes/kubelet-plugins/net/exec
      - /etc/systemd/system/netplugin.service
      - /etc/systemd/system/netmaster.service
      - /etc/systemd/system/aci-gw.service
      - /usr/bin/aci_gw.sh
      - /usr/bin/netplugin
      - /usr/bin/netmaster
      - /usr/bin/netctl
      - /usr/bin/contivctl
      - /etc/default/netplugin
      - /etc/default/netmaster
      - /etc/kubernetes/config
      - /etc/kubernetes/kubelet
      - /etc/kubernetes
